### PR TITLE
Code cleanup + fix some bugs

### LINKED ISSUE #136: The data loading may show undefined behaviors, if users change the stored data manually.
such that it's possible lead to flaw if user tries to modify the data files manually.

### PR DESCRIPTION
**Pull request by chooyikai**
Fixes #136 and #140

### CODE REVIEW

File: src/main/java/seedu/duke/storage/ModuleListStorage.java [hunk 1]
```diff
@@ -47,7 +51,10 @@
         ArrayList<String> moduleCodes = new ArrayList<>();
         for (Module m : arrayList) {
             if (moduleCodes.contains(m.getModuleCode())) {
-                throw new DuplicateModuleException();
+                throw new DuplicateModuleException(m.getModuleCode());
+            }
+            if (m.getModularCredit() > MAXIMUM_MODULAR_CREDITS || m.getModularCredit() < 0) {
+                throw new InvalidModuleException(m.getModuleCode(), m.getModularCredit());
```
Comment (Ch40gRv1-Mu) [inline src/main/java/seedu/duke/storage/ModuleListStorage.java:57]: After discussing with Yikai, I will put the logic, together with the loading logic in Main class to a static class to keep the ModuleList class simple.

**Review by Ch40gRv1-Mu — APPROVED** [review]
Good optimization, leaves a comment on the ModuleListStorage after discussing with Yikai.
