### PR TITLE
Added JavaDoc, bug fixes, and  allowing "" for editing a task parameter

### LINKED ISSUE #195: Unable to remove optional parameters with edit command
Feeding a blank string should allow the removal of optional parameters, but currently such input is just rejected by the command parser.

E.g. running `edit task 1 -t ""` should remove the estimated time remaining from the task in question.

### PR DESCRIPTION
**Pull request by heekit73098**

### CODE REVIEW

File: src/main/java/seedu/duke/data/Module.java [hunk 1]
```diff
@@ -60,7 +60,8 @@ public void setModuleGrade(String moduleGrade) {
     }
 
     /**
-     * Returns the task list associated with the module.
+     * Gets the task list associated with the module.
+     * @return Task List associated with the module
```
Comment (Ch40gRv1-Mu) [inline src/main/java/seedu/duke/data/Module.java]: "Task list" :)

File: src/main/java/seedu/duke/data/Module.java [hunk 2]
```diff
@@ -72,13 +73,16 @@ public void setTaskArrayList(ArrayList<Task> list) {
...
         taskList.addTask(task);
     }
 
     /**
      * Formats the module and its associated tasks according to given parameters.
+     * @param showCompletedTasks Whether completed tasks should be shown or not
+     * @return The string of all tasks, depending on whether completed tasks should be shown
      */
     public String printModuleTaskList(boolean showCompletedTasks) {
         return this + LS + taskList.getAllTasks(INDENT, showCompletedTasks);
```
Comment (Ch40gRv1-Mu) [inline src/main/java/seedu/duke/data/Module.java]: Suggests to modify the method name to getModuleTaskList or moduleTaskListToString, or something similar, because I don't think it prints here.

Comment (Ch40gRv1-Mu) [reply src/main/java/seedu/duke/data/Module.java]: This is not for this PR specificly, but just a small suggestion.

**Review by Ch40gRv1-Mu — CHANGES_REQUESTED** [review]
Good optimization, only one tiny case issue.

File: src/main/java/seedu/duke/data/Module.java (hunk 1 above)
Comment (heekit73098) [reply src/main/java/seedu/duke/data/Module.java]: yup changed

File: src/main/java/seedu/duke/data/Module.java (hunk 2 above)
Comment (heekit73098) [reply src/main/java/seedu/duke/data/Module.java]: renamed to `stringifyModuleTaskList`
