### PR TITLE
added javadoc and fixed some bugs

### LINKED ISSUE #163: [PE-D] It is possible to add a space in the the task list which is essentially nothing
-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: wraineflores/ped#5

### PR DESCRIPTION
**Pull request by Yzkkk**
added some javadoc and Junit tests

### CODE REVIEW

File: src/main/java/seedu/duke/commands/HelpCommand.java [hunk 1]
```diff
@@ -46,6 +46,9 @@ public HelpCommand(String command) {
         this.command = command;
     }
 
+    /**
+     * Display help messages for different commands.
```
Comment (ngys117) [inline src/main/java/seedu/duke/commands/HelpCommand.java]: I believe it should be Displays not Display as part of convention

File: src/main/java/seedu/duke/commands/SaveCommand.java [hunk 2]
```diff
@@ -19,6 +19,11 @@
 
     private Storage storage;
 
+    /**
+     * Save the existing list of general tasks and modules.
```
Comment (ngys117) [inline src/main/java/seedu/duke/commands/SaveCommand.java]: Saves instead of save

File: src/main/java/seedu/duke/data/TaskList.java [hunk 3]
```diff
@@ -47,6 +47,13 @@ public Task removeTask(int index) throws NoSuchTaskException {
         return task;
     }
 
+    /**
+     * Adds tag to the task list.
+     *
+     * @param tagDescription The description of tag that is inputted by user
+     * @param index The task number to be added with tag
+     * @throws NoSuchTaskException if the user-supplied index is out of bounds
```
Comment (ngys117) [inline src/main/java/seedu/duke/data/TaskList.java]: Same punctuation suggestion as line 39 in TaskList, as well as capitalize the first letter in the description.

File: src/main/java/seedu/duke/data/TaskList.java [hunk 4]
```diff
@@ -36,7 +36,7 @@ public Task addTask(Task t) {
 
     /**
      * Removes the specified task from the task list.
-     * @param index The task number to be removed.
+     * @param index The task number to be removed
```
Comment (ngys117) [inline src/main/java/seedu/duke/data/TaskList.java]: I think there should be punctuation (full stop) at the end of each parameter description?

File: src/main/java/seedu/duke/data/TaskList.java [hunk 5]
```diff
@@ -57,6 +64,14 @@ public Task addTag(String tagDescription, int index) throws NoSuchTaskException
         return task;
     }
 
+    /**
+     * Removes tag from the task list.
+     *
+     * @param tagDescription The description of tag that is inputted by user
+     * @param index The task number to remove the tag
+     * @throws NoSuchTaskException if the user-supplied index is out of bounds
+     * @throws NoSuchTagException if the user-supplied tag to be removed does not exist
```
Comment (ngys117) [inline src/main/java/seedu/duke/data/TaskList.java]: Punctuation and capitalization as mentioned above

File: src/main/java/seedu/duke/data/TaskList.java [hunk 6]
```diff
@@ -91,6 +106,7 @@ public Task getTask(int index) {
 
     /**
      * Formats all tasks in the task list as a pretty printed string.
+     *
      * @param indent string representing the indentation level for each task item
      * @param showCompletedTasks whether completed tasks should be listed
```
Comment (ngys117) [inline src/main/java/seedu/duke/data/TaskList.java]: Could you help capitalize the first letter of the  parameter descriptions? Must have been missed before.

File: src/main/java/seedu/duke/data/TaskList.java [hunk 7]
```diff
@@ -115,6 +131,7 @@ public String getAllTasks(String indent, boolean showCompletedTasks) {
 
     /**
      * Formats all tasks in the task list with a matching tag as a pretty printed string.
+     *
      * @param indent string representing the indentation level for each task item
      * @param tag the tag to be matched
      * @param showCompletedTasks whether completed tasks should be listed
```
Comment (ngys117) [inline src/main/java/seedu/duke/data/TaskList.java]: Capitalize the first letter of the descriptions here as well perhaps

File: src/main/java/seedu/duke/util/Grades.java [hunk 8]
```diff
@@ -16,6 +16,9 @@
 import static seedu.duke.util.StringConstants.PLUS;
 import static seedu.duke.util.StringConstants.DASH;
 
+/**
+ * Enum for grades and their associated grade points.
```
Comment (ngys117) [inline src/main/java/seedu/duke/util/Grades.java]: Maybe let's not use enum and type enumeration out in full?

File: src/main/java/seedu/duke/data/TaskList.java [hunk 9]
```diff
@@ -47,6 +47,13 @@ public Task removeTask(int index) throws NoSuchTaskException {
         return task;
     }
 
+    /**
+     * Adds tag to the task list.
+     *
+     * @param tagDescription The description of tag that is inputted by user
+     * @param index The task number to be added with tag
```
Comment (ngys117) [inline src/main/java/seedu/duke/data/TaskList.java]: Index isn't really the same as task number. Maybe change the description to `Index of task to be added with tag.`

File: src/main/java/seedu/duke/data/TaskList.java [hunk 10]
```diff
@@ -57,6 +64,14 @@ public Task addTag(String tagDescription, int index) throws NoSuchTaskException
         return task;
     }
 
+    /**
+     * Removes tag from the task list.
+     *
+     * @param tagDescription The description of tag that is inputted by user
+     * @param index The task number to remove the tag
```
Comment (ngys117) [inline src/main/java/seedu/duke/data/TaskList.java]: Index isn't really the same as task number. Maybe change the description to `Index of task to be added with tag.`

**Review by ngys117 — CHANGES_REQUESTED** [review]
Several changes suggested

**Comment by Yzkkk** [comment]
commented out some of the Junit tests since exceptions and error messages need to be changed.

**Comment by Yzkkk** [comment]
"Invalid compulsory parameters. Please check and try again." is replaced by some of the error messages below.

Going to add more exceptions for different commands later on.

Screenshot (856)
Screenshot (857)
Screenshot (858)

**Comment by Yzkkk** [comment]
Screenshot (860)

File: src/main/java/seedu/duke/parsers/GradeParser.java [hunk 11]
```diff
@@ -18,14 +18,15 @@
     // Unescaped regex for testing:
     // ((?<moduleCode>\w+)(\s+(?<moduleGrade>(?i)(CU|CS|[A-B][+-]?|[C-D][+]?|F|S|U))))(?<invalid>.*)
     private static final String GRADE_FORMAT = "((?<moduleCode>\\w+)(\\s+"
-            + "(?<moduleGrade>(?i)(CU|CS|[A-B][+-]?|[C-D][+]?|F|S|U))))(?<invalid>.*)";
+            + "(?<moduleGrade>(?i)(CU|CS|[A-B][+-]?|[C-D][+]?|F|S|U)|(?<invalidModuleGrade>.*))))(?<invalid>.*)";
```
Comment (heekit73098) [inline src/main/java/seedu/duke/parsers/GradeParser.java:21]: The regex should make invalid always be null, maybe invalid can be removed in this case

**Comment by Yzkkk** [comment]
The expected output for empty string is shown below. 

We can include in UG saying that our program doesn't recognise empty strings after optional param flags, so if users inputted that way our program is going to treat it as excess param.

Screenshot (862)

File: src/main/java/seedu/duke/parsers/AddParser.java [hunk 12]
```diff
@@ -50,10 +51,10 @@
      *                                                      Does not accept " as a valid character.
      *
      * (?<invalid>.*)                                    -- matches [invalid]
-     *                                                      Any other input which do not fit in any of the above
+     *                                                      Any other excess inputs
      */
 
-    private static final String ADD_FORMAT = "(task\\s+\\\"(?<taskName>[^\\\"]+)\\\"(\\s+-m\\s+(?<taskModule>\\w+))?"
+    private static final String ADD_FORMAT = "(task\\s+\\\"(?<taskName>[^\\\"]+)\\\"(\\s+((-m)\\s+|(?<invalidFlag>.*))(?<taskModule>\\w+))?"
```
Comment (heekit73098) [inline src/main/java/seedu/duke/parsers/AddParser.java]: can you check if the regex correctly accepts `add task "task" -d "description"`, based on my online testing, it seems that -d "descriptio" is captured as invalid flag

File: src/main/java/seedu/duke/parsers/Parser.java [hunk 13]
```diff
@@ -66,9 +68,30 @@ public Parser() {
         if (groupNames.contains(INVALID)) {
             String invalidInput = parsedCommand.get(INVALID);
             if (!Objects.isNull(invalidInput) && !invalidInput.isBlank()) {
-                throw new InvalidInputException(invalidInput);
+                throw new InvalidExcessArgumentException(invalidInput);
```
Comment (heekit73098) [inline src/main/java/seedu/duke/parsers/Parser.java]: I think this exceeds 30 LOC based on the guidelines, so consider extracting them into another function

**Review by heekit73098 — CHANGES_REQUESTED** [review]
A few comments on regex and code quality

File: src/main/java/seedu/duke/parsers/AddParser.java (hunk 12 above)
Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/AddParser.java]: Hmm weird, it seems to work well on my side.

Screenshot (864)

Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/AddParser.java]: But yes, i do notice if I enter `add task "task" -a "description"`, it is going to eat the last letter.

Not very sure what to add to the regex to fix this.

Screenshot (865)

File: src/main/java/seedu/duke/parsers/GradeParser.java (hunk 11 above)
Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/GradeParser.java:21]: Nop, in this case, the invalid will be capturing excess arguments at the back of each command.

For eg,

Screenshot (867)

File: src/main/java/seedu/duke/parsers/Parser.java (hunk 13 above)
Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/Parser.java]: Yup you are right, extracted.

File: src/main/java/seedu/duke/parsers/AddParser.java (hunk 12 above)
Comment (heekit73098) [reply src/main/java/seedu/duke/parsers/AddParser.java]: maybe consider shifting `(?<taskModule>\w+)` to before the `|` like `(\s+((-m)\s+(?<taskModule>\w+)|(?<invalidFlag>.*)))?`

Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/AddParser.java]: That worked but the output will be `'-a CS2101'`.

Anyways, Ive changed it to `(\s+((-m|(?<invalidFlag>.*))\s+(?<taskModule>\w+)))?` and now it identify invalid flag to be `'-a'`. Thanks!

Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/AddParser.java]: Screenshot (869)

**Comment by Yzkkk** [comment]
Here are some examples of error messages.
Screenshot (879)

**Comment by Yzkkk** [comment]
The EditCommand seems to have some bugs for the regex. Not sure which part though, I've done it the same way as AddCommand and Addcommand is alright.

Screenshot (877)

**Comment by heekit73098** [comment]
Could be cause the invalidTaskNameFlag captures the `-d` instead, as the regex first checks for -n, and since it is not present, it proceeds to match the input in the invalidTaskNameFlag group. Maybe to fix u could have one invalid flag group that captures everything except for `-d`, `-n` and `-t` before capturing the correct group

**Comment by Yzkkk** [comment]
> Could be cause the invalidTaskNameFlag captures the `-d` instead, as the regex first checks for -n, and since it is not present, it proceeds to match the input in the invalidTaskNameFlag group. Maybe to fix u could have one invalid flag group that captures everything except for `-d`, `-n` and `-t` before capturing the correct group

Yea, but that way the error message will not be very descriptive...

I've also documented the regex of editParser but still couldn't figure out what is wrong

File: src/main/java/seedu/duke/parsers/EditParser.java [hunk 14]
```diff
@@ -26,23 +34,68 @@
...
+     * ((task\s+(?<taskNumber>\d+|(?<invalidNumber>.*))      -- matches [task taskNumber].
+     *
+     * (\s+(-m|(?<invalidModFlag>.*))\s+(?<taskModule>\w+))? -- matches [-m taskModule] if present. Optional
+     *                                                          Note that taskModule does not require "", but must be a
+     *                                                          single word composed of [a-zA-Z0-9_].
+     *
+     * (?=\s+-n\s+\"[^\"]+\"|\s+-d\s+\"[^\"]+\"              -- matches flags -n, -d, -t.
+     * |\s+-t\s+\"[^\"]+\")
+     *
+     * (\s+(-n|(?<invalidTaskNameFlag>.*))                   -- matches [-n "taskName"] or
```
Comment (heekit73098) [inline src/main/java/seedu/duke/parsers/EditParser.java:47]: correct me if im wrong, but isnt the issue here because either `-d` or `-t` entered will be flagged as `invalidTaskNameFlag` because the regex matches the group in order and `(?<invalidTaskNameFlag>.*)` captures anything that is not `-n`. Im not sure how do you want to make the error message more descriptive since the parameter here can be either `-d`, `-n` or `-t`, so unless the user has specified `-d` and then entered something invalid, only then can we conclude that the TASK_DESCRIPTION is wrong. So if that is the case, then if theres an error, then we can check which of the 3 optional parameters is used and give the error message as such, or if all 3 optional parameters are not captured, then it means the flag is incorrect

Comment (heekit73098) [reply src/main/java/seedu/duke/parsers/EditParser.java:47]: > So if that is the case, then if theres an error, then we can check which of the 3 optional parameters is used and give the error message as such, or if all 3 optional parameters are not captured, then it means the flag is incorrect

Not in the regex but as logic code i guess

Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/EditParser.java:47]: >if all 3 optional parameters are not captured, then it means the flag is incorrect

True, yea I've made some changes and grouped the 3 flags together. Currently, the code doesn't have the previous bugs as commented above, it's also able to give error messages after capturing empty spaces after the flags, for eg `-d " "` . But once I have `|(?<invalidFlag>.*)` after `(-n|-d|-t)` , and I enter a random flag, the random flag will be captured by `invalid` instead of `invalidFlag`. So as for now I didn't include the `<invalidFlag>` yet, and the error message for invalid flag is still the very general `"Invalid compulsory parameters."`.

File: src/main/java/seedu/duke/parsers/EditParser.java [hunk 15]
```diff
@@ -52,20 +104,39 @@ public Command parseCommand(String userInput) throws ModHappyException {
...
         }
-
         if (!Objects.isNull(taskNumberString)) {
             int taskIndex;
             try {
                 taskIndex = Integer.parseInt(taskNumberString) - 1;
             } catch (NumberFormatException e) {
                 throw new InvalidNumberException(TASK_NUMBER_STR);
             }
+            if (!Objects.isNull(taskName)) {
```
Comment (heekit73098) [inline src/main/java/seedu/duke/parsers/EditParser.java]: This looks like it exceeds 30 LOC

**Review by heekit73098 — COMMENTED** [review]
Otherwise LGTM

File: src/main/java/seedu/duke/parsers/EditParser.java (hunk 15 above)
Comment (Yzkkk) [reply src/main/java/seedu/duke/parsers/EditParser.java]: yea extracted
