### PR TITLE
Ui Bug fixes and some code refactoring

### LINKED ISSUE #122: When adding a task to an empty module task list or empty general list, it will print "you currently have 1 tasks on the list".

### LINKED ISSUE #137: [PE-D] Forgot to remove head words
-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: wraineflores/ped#1

### LINKED ISSUE #153: [PE-D] Documentation for duration is not consistent with functionality
**Describe the bug**

User doc states "Any positive number less than one billion (1000000000), including decimals." for DURATION_AMOUNT, but I can still add tasks 1 bil hours. (fails on 1bil+1)

**To Reproduce**
1. Add a task with 1 billion hours.

**Expected behavior**

The task should not be added.

**Screenshots**

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: IncompetentDev/ped#4

### LINKED ISSUE #164: [PE-D] Unnecessary information in help message
There is no flag in the command used.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: tuan0369/ped#4

### LINKED ISSUE #165: [PE-D] Cosmetic bug when editing non-existent task
**Describe the bug**

Editing a zero-indexed task prints a IndexOutOfBoundsException message. (Does not crash)

**To Reproduce**

1. Type `edit task 20-0 -n "asd"`, make sure task 200 doesn't exist

**Expected behavior**

A more graceful message informing the user of the error, instead of only IndexOutOfboundsException

Screenshots

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: IncompetentDev/ped#5

### PR DESCRIPTION
**Pull request by ngys117**

### CODE REVIEW

**Comment by ngys117** [comment]
Fixes #122, #137, #153, #164, #165

File: src/main/java/seedu/duke/commands/AddCommand.java [hunk 1]
```diff
@@ -72,12 +72,12 @@ public CommandResult execute(ModuleList moduleList, Configuration configuration)
...
                 targetModule = moduleList.getModule(targetModuleName);
-                if (Objects.isNull(targetModule)) {
-                    throw new NoSuchModuleException();
-                }
+            }
+            if (Objects.isNull(targetModule)) {
+                throw new NoSuchModuleException();
             }
             TaskList taskList = targetModule.getTaskList();
-            res = String.format(ADD_TASK_MESSAGE, targetModule, taskList.addTask(newTask), taskList.size());
```
Comment (Ch40gRv1-Mu) [inline src/main/java/seedu/duke/commands/AddCommand.java:80]: Does this mean that the size of tasks in list will not be shown?

File: src/main/java/seedu/duke/commands/DeleteCommand.java [hunk 2]
```diff
@@ -49,18 +49,18 @@ public DeleteCommand(int taskIndex, String taskModule) {
     public CommandResult execute(ModuleList moduleList, Configuration configuration) throws ModHappyException {
         if (taskIndex < 0) {
             deleteModule(moduleList);
+            return new CommandResult(result);
+        }
```
Comment (Ch40gRv1-Mu) [inline src/main/java/seedu/duke/commands/DeleteCommand.java:53]: I suggest change the magic logic here, at least add comments explaining what taskIndex < 0 mean

Comment (Ch40gRv1-Mu) [reply src/main/java/seedu/duke/commands/DeleteCommand.java:53]: Also the EditCommand remains unchanged. https://github.com/ngys117/tp/blob/282df85449c6c823bfcc5de7da3ce1e1108924d7/src/main/java/seedu/duke/commands/EditCommand.java#L105-L107
Screen Shot 2022-04-03 at 10 48 11 PM

**Review by Ch40gRv1-Mu — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/duke/commands/DeleteCommand.java [hunk 3]
```diff
@@ -71,6 +71,9 @@ public CommandResult execute(ModuleList moduleList, Configuration configuration)
      */
     public void deleteModule(ModuleList moduleList) throws NoSuchModuleException {
         Module targetModule = moduleList.getModule(moduleCode);
+        if (Objects.isNull(targetModule)) {
```
Comment (heekit73098) [inline src/main/java/seedu/duke/commands/DeleteCommand.java:74]: would throwing `NoSuchModuleException` in `getModule` instead of returning null be more concise since theres no need to check for null all the time?

Comment (ngys117) [reply src/main/java/seedu/duke/commands/DeleteCommand.java:74]: That is actually a good point, but there would need to be refactoring for every other Command that uses getModule as well. I think the original idea was that the logic for validation should be done by Command instead of ModuleList, but that is not the case for TaskList. (Maybe I remembered it wrong)

File: src/main/java/seedu/duke/commands/DeleteCommand.java (hunk 2 above)
Comment (ngys117) [reply src/main/java/seedu/duke/commands/DeleteCommand.java:53]: Ah, missed the edit bug. Thanks for the catch.

File: src/main/java/seedu/duke/commands/AddCommand.java (hunk 1 above)
Comment (ngys117) [reply src/main/java/seedu/duke/commands/AddCommand.java:80]: Yes, I think we agreed to remove the message as it does not add value to user

File: src/main/java/seedu/duke/commands/DeleteCommand.java (hunk 3 above)
Comment (ngys117) [reply src/main/java/seedu/duke/commands/DeleteCommand.java:74]: I'll do this in a different PR
